---
apiVersion: v1
kind: Service
metadata:
  name: npuzzlex-backend-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 8080
  selector:
    name: npuzzlex-backend